<?php

namespace Fenchy\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EmailChangeRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailChangeRequestRepository extends EntityRepository
{
}
