<?php

namespace Fenchy\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NotificationGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationGroupRepository extends EntityRepository
{
}
