<?php

namespace Proxies\__CG__\Fenchy\NoticeBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Notice extends \Fenchy\NoticeBundle\Entity\Notice implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function getTitle()
    {
        $this->__load();
        return parent::getTitle();
    }

    public function setTitle($title)
    {
        $this->__load();
        return parent::setTitle($title);
    }

    public function getContent()
    {
        $this->__load();
        return parent::getContent();
    }

    public function setContent($content)
    {
        $this->__load();
        return parent::setContent($content);
    }

    public function getAllowed()
    {
        $this->__load();
        return parent::getAllowed();
    }

    public function setAllowed($allowed)
    {
        $this->__load();
        return parent::setAllowed($allowed);
    }

    public function getAllowedName($allowed = NULL)
    {
        $this->__load();
        return parent::getAllowedName($allowed);
    }

    public function getStartDateDate()
    {
        $this->__load();
        return parent::getStartDateDate();
    }

    public function getStartTime()
    {
        $this->__load();
        return parent::getStartTime();
    }

    public function getType()
    {
        $this->__load();
        return parent::getType();
    }

    public function setType(\Fenchy\NoticeBundle\Entity\Type $type)
    {
        $this->__load();
        return parent::setType($type);
    }

    public function getRootType()
    {
        $this->__load();
        return parent::getRootType();
    }

    public function getUser()
    {
        $this->__load();
        return parent::getUser();
    }

    public function setUser(\Fenchy\UserBundle\Entity\User $user)
    {
        $this->__load();
        return parent::setUser($user);
    }

    public function getGallery()
    {
        $this->__load();
        return parent::getGallery();
    }

    public function setGallery(\Fenchy\GalleryBundle\Entity\Gallery $gallery)
    {
        $this->__load();
        return parent::setGallery($gallery);
    }

    public function getMainImage()
    {
        $this->__load();
        return parent::getMainImage();
    }

    public function getAvatar()
    {
        $this->__load();
        return parent::getAvatar();
    }

    public function getValues()
    {
        $this->__load();
        return parent::getValues();
    }

    public function setValues(\Doctrine\Common\Collections\ArrayCollection $values)
    {
        $this->__load();
        return parent::setValues($values);
    }

    public function addValue(\Fenchy\NoticeBundle\Entity\Value $value)
    {
        $this->__load();
        return parent::addValue($value);
    }

    public function removeValue(\Fenchy\NoticeBundle\Entity\Value $value)
    {
        $this->__load();
        return parent::removeValue($value);
    }

    public function getDraft()
    {
        $this->__load();
        return parent::getDraft();
    }

    public function setDraft($draft)
    {
        $this->__load();
        return parent::setDraft($draft);
    }

    public function hasValue(\Fenchy\NoticeBundle\Entity\PropertyType $property, $val)
    {
        $this->__load();
        return parent::hasValue($property, $val);
    }

    public function getLink()
    {
        $this->__load();
        return parent::getLink();
    }

    public function setLink($link)
    {
        $this->__load();
        return parent::setLink($link);
    }

    public function getOptionValueName($id, $val)
    {
        $this->__load();
        return parent::getOptionValueName($id, $val);
    }

    public function getOptionValue($property)
    {
        $this->__load();
        return parent::getOptionValue($property);
    }

    public function selectParent(\Doctrine\Common\Collections\ArrayCollection $types)
    {
        $this->__load();
        return parent::selectParent($types);
    }

    public function getValuesList()
    {
        $this->__load();
        return parent::getValuesList();
    }

    public function getCreatedAt()
    {
        $this->__load();
        return parent::getCreatedAt();
    }

    public function setCreatedAt($date)
    {
        $this->__load();
        return parent::setCreatedAt($date);
    }

    public function getDirection()
    {
        $this->__load();
        return parent::getDirection();
    }

    public function addFacebookFeed(\Fenchy\NoticeBundle\Entity\FacebookFeed $facebookFeed)
    {
        $this->__load();
        return parent::addFacebookFeed($facebookFeed);
    }

    public function removeFacebookFeed(\Fenchy\NoticeBundle\Entity\FacebookFeed $facebookFeed)
    {
        $this->__load();
        return parent::removeFacebookFeed($facebookFeed);
    }

    public function getFacebookFeed()
    {
        $this->__load();
        return parent::getFacebookFeed();
    }

    public function getPutOnFb()
    {
        $this->__load();
        return parent::getPutOnFb();
    }

    public function setPutOnFb($put_on_fb)
    {
        $this->__load();
        return parent::setPutOnFb($put_on_fb);
    }

    public function canEdit()
    {
        $this->__load();
        return parent::canEdit();
    }

    public function getStartDate()
    {
        $this->__load();
        return parent::getStartDate();
    }

    public function setStartDate($startDate)
    {
        $this->__load();
        return parent::setStartDate($startDate);
    }

    public function setEndDate($endDate)
    {
        $this->__load();
        return parent::setEndDate($endDate);
    }

    public function getEndDate()
    {
        $this->__load();
        return parent::getEndDate();
    }

    public function setLocation(\Fenchy\UtilBundle\Entity\Location $location)
    {
        $this->__load();
        return parent::setLocation($location);
    }

    public function getLocation()
    {
        $this->__load();
        return parent::getLocation();
    }

    public function getDatesDiff()
    {
        $this->__load();
        return parent::getDatesDiff();
    }

    public function getStickers()
    {
        $this->__load();
        return parent::getStickers();
    }

    public function setStickers(\Doctrine\Common\Collections\ArrayCollection $stickers)
    {
        $this->__load();
        return parent::setStickers($stickers);
    }

    public function addSticker(\Fenchy\UtilBundle\Entity\Sticker $sticker)
    {
        $this->__load();
        return parent::addSticker($sticker);
    }

    public function removeSticker(\Fenchy\UtilBundle\Entity\Sticker $sticker)
    {
        $this->__load();
        return parent::removeSticker($sticker);
    }

    public function setReviews(\Doctrine\Common\Collections\ArrayCollection $reviews)
    {
        $this->__load();
        return parent::setReviews($reviews);
    }

    public function addReview(\Fenchy\NoticeBundle\Entity\Review $review)
    {
        $this->__load();
        return parent::addReview($review);
    }

    public function removeReview(\Fenchy\NoticeBundle\Entity\Review $review)
    {
        $this->__load();
        return parent::removeReview($review);
    }

    public function getReviews()
    {
        $this->__load();
        return parent::getReviews();
    }

    public function toJsonArray()
    {
        $this->__load();
        return parent::toJsonArray();
    }

    public function getOnDashboard()
    {
        $this->__load();
        return parent::getOnDashboard();
    }

    public function setOnDashboard($on_dashboard)
    {
        $this->__load();
        return parent::setOnDashboard($on_dashboard);
    }

    public function getSlug()
    {
        $this->__load();
        return parent::getSlug();
    }

    public function setSlug($slug)
    {
        $this->__load();
        return parent::setSlug($slug);
    }

    public function getTypeSlug()
    {
        $this->__load();
        return parent::getTypeSlug();
    }

    public function getIcon()
    {
        $this->__load();
        return parent::getIcon();
    }

    public function getTags()
    {
        $this->__load();
        return parent::getTags();
    }

    public function setTags($tags)
    {
        $this->__load();
        return parent::setTags($tags);
    }

    public function getValueByProperty(\Fenchy\NoticeBundle\Entity\PropertyType $property)
    {
        $this->__load();
        return parent::getValueByProperty($property);
    }

    public function getDictionaries()
    {
        $this->__load();
        return parent::getDictionaries();
    }

    public function setDictionaries($dictionaries)
    {
        $this->__load();
        return parent::setDictionaries($dictionaries);
    }

    public function addDictionary(\Fenchy\NoticeBundle\Entity\Dictionary $dictionary)
    {
        $this->__load();
        return parent::addDictionary($dictionary);
    }

    public function removeDictionary(\Fenchy\NoticeBundle\Entity\Dictionary $dictionary)
    {
        $this->__load();
        return parent::removeDictionary($dictionary);
    }

    public function get($property)
    {
        $this->__load();
        return parent::get($property);
    }

    public function releaseReviews()
    {
        $this->__load();
        return parent::releaseReviews();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'title', 'slug', 'content', 'allowed', 'draft', 'link', 'created_at', 'start_date', 'end_date', 'on_dashboard', 'tags', 'type', 'user', 'gallery', 'values', 'facebook_feed', 'location', 'stickers', 'reviews', 'dictionaries');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}