<?php

namespace Proxies\__CG__\Fenchy\NoticeBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Value extends \Fenchy\NoticeBundle\Entity\Value implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function getNotice()
    {
        $this->__load();
        return parent::getNotice();
    }

    public function setNotice(\Fenchy\NoticeBundle\Entity\Notice $notice)
    {
        $this->__load();
        return parent::setNotice($notice);
    }

    public function getProperty()
    {
        $this->__load();
        return parent::getProperty();
    }

    public function setProperty(\Fenchy\NoticeBundle\Entity\PropertyType $property)
    {
        $this->__load();
        return parent::setProperty($property);
    }

    public function getValue($raw = true)
    {
        $this->__load();
        return parent::getValue($raw);
    }

    public function setValue($value)
    {
        $this->__load();
        return parent::setValue($value);
    }

    public function hasValue($val)
    {
        $this->__load();
        return parent::hasValue($val);
    }

    public function getValueAsString()
    {
        $this->__load();
        return parent::getValueAsString();
    }

    public function setValueFromOptionByString($name)
    {
        $this->__load();
        return parent::setValueFromOptionByString($name);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'value', 'notice', 'property');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}