<?php

namespace Fenchy\UserBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class WidgetsController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Fenchy\UserBundle\Controller\WidgetsController();
        return $instance;
    }
}
