<?php

namespace Fenchy\GalleryBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class PunkaveController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Fenchy\GalleryBundle\Controller\PunkaveController();
        return $instance;
    }
}
