<?php

namespace Fenchy\UtilBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class StickerController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Fenchy\UtilBundle\Controller\StickerController();
        return $instance;
    }
}
