<?php

namespace Fenchy\RegularUserBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class MessageController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Fenchy\RegularUserBundle\Controller\MessageController();
        return $instance;
    }
}
