imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    trust_proxy_headers: false # Whether or not the Request object should trust proxy headers (X_FORWARDED_FOR/HTTP_CLIENT_IP)
    session:         ~
    
# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals: 
        facebook_app_id: %facebook_app_id%
        default_profile_picture: images/default_profile_picture.png
        default_picture: images/default_picture.png
        notice_days_before: %notice_days_before%
        notice_days_after: %notice_days_after%
        activities_to_display: 4
        notice_menu_property: %notice_menu_property%
        default_location: Berlin, Germany

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
#    bundles:        [ PunkAveFileUploaderBundle ]
    bundles:        [  ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar


# Doctrine Configuration
doctrine:
    dbal:
        default_connection:   default
        connections:
            default:
                driver:   %database_driver%
                host:     %database_host%
                port:     %database_port%
                dbname:   %database_name%
                user:     %database_user%
                password: %database_password%
                charset:  UTF8
                mapping_types:
                    geography: geography
                    geometry: geometry
        types:
            geography: Fenchy\UtilBundle\Types\GeographyType
            geometry:  Fenchy\UtilBundle\Types\GeometryType

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        entity_managers:
            default:
                dql:
                    string_functions:
                        to_tsquery: Fenchy\UtilBundle\DQL\ToTsQuery
                        to_tsvector: Fenchy\UtilBundle\DQL\ToTsVector
                        ts_search: Fenchy\UtilBundle\DQL\TsSearch
                        ts_rank_cd: Fenchy\UtilBundle\DQL\TsRankCd
                        similarity: Fenchy\UtilBundle\DQL\Similarity
                        concatSB: Fenchy\UtilBundle\DQL\ConcatSB
                        geoDistance: Fenchy\UtilBundle\DQL\GeoDistance
                        date: Fenchy\UtilBundle\DQL\Date
                        postGIS_ST_Distance: Fenchy\UtilBundle\DQL\PostGISSTDistance
                        postGIS_ST_DWithin: Fenchy\UtilBundle\DQL\PostGISSTDWithin
                        postGIS_KNN_Operator: Fenchy\UtilBundle\DQL\PostGISKNNOperator
                
                auto_mapping: true
                filters:
                    softdeleteable:
                        class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                        enabled: true
                mappings:
                # DoctrineExtensions
                    gedmo_translatable:
                        type: annotation
                        alias: Gedmo
                        prefix: Gedmo\Translatable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
                        is_bundle: false
                    gedmo_translator:
                        type: annotation
                        alias: Gedmo
                        prefix: Gedmo\Translator\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translator/Entity"
                        is_bundle: false
                    gedmo_loggable:
                        type: annotation
                        alias: Gedmo
                        prefix: Gedmo\Loggable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                        is_bundle: false
                    gedmo_tree:
                        type: annotation
                        alias: Gedmo
                        prefix: Gedmo\Tree\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
                        is_bundle: false
# DoctrineExtensions
stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default:
            timestampable: true
            softdeleteable: true

# Swiftmailer Configuration
swiftmailer:
    transport:  %mailer_transport%
    host:       %mailer_host%
    username:   %mailer_user%
    password:   %mailer_password%
    encryption: %mailer_encryption%
    auth_mode:  %mailer_auth_mode%
    port:       %mailer_port%
#    spool:
#      type: file
#      path: "%kernel.root_dir%/Spool"
#    antiflood:
#      threshold: 1000
    
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Fenchy\UserBundle\Entity\User
    service:
        mailer: fos_user.mailer.twig_swift
    from_email:
        address:        %from_email%
        sender_name:    %from_name%
    registration:
        form:
            type: fenchy_userbundle_registration
            name: registration
            handler: fenchy.registration.form.handler
        confirmation:
            enabled:    true
            template: UserBundle:Registration:email.html.twig
    resetting:
      email:
        from_email:
          address:        %from_email%
          sender_name:    %from_name%
        template:   UserBundle:Resetting:email.html.twig
      token_ttl: 86400
    profile:
      form:
        type: fos_user_profile
            
            
fos_twitter:
    file: %kernel.root_dir%/../vendor/kertz/twitteroauth/twitteroauth/twitteroauth.php
    consumer_key: %twitter_consumer_key%
    consumer_secret: %twitter_consumer_secret%
    callback_url: %twitter_callback_url%

fos_facebook:
    #file:   %kernel.root_dir%/../vendor/facebook/php-sdk/src/base_facebook.php
    alias:  facebook
    app_id: %facebook_app_id%
    secret: %facebook_secret%
    cookie: true
    permissions: [email, user_birthday, user_location]
    
services:
    fenchy.twig.extension.debug:
        class: Twig_Extension_Debug
        tags:
             - { name: 'twig.extension' }
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }
    kernel.listener.locale_listener:
        class: Fenchy\FrontendBundle\Listener\LocaleListener
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelRequest }
        arguments: ["@service_container"]
    gedmo.listener.sluggable:
        class: Gedmo\Sluggable\SluggableListener
        tags:
          - { name: doctrine.event_subscriber, connection: default }
        calls:
          - [ setAnnotationReader, [ @annotation_reader ] ]
    punk_ave.file_uploader:
        class: Fenchy\GalleryBundle\Services\FileUploader
        arguments:
          - file_base_path: '%file_uploader.file_base_path%'
            web_base_path: '%file_uploader.web_base_path%'
            request: '@request'
            file_manager: '@punk_ave.file_uploader_file_manager'
            allowed_extensions: '%file_uploader.allowed_extensions%'
            sizes: '%file_uploader.sizes%'
            originals: '%file_uploader.originals%'
            crop: '%file_uploader.crop%'
        scope: request
    punk_ave.file_uploader_file_manager:
        class: Fenchy\GalleryBundle\Services\FileManager
        arguments:
          # For bc reasons we're not changing the names of the parameters
          - file_base_path: '%file_uploader.file_base_path%'


