<?php

namespace Proxies\__CG__\Fenchy\UserBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class NotificationGroup extends \Fenchy\UserBundle\Entity\NotificationGroup implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function setName($name)
    {
        $this->__load();
        return parent::setName($name);
    }

    public function getNotifications()
    {
        $this->__load();
        return parent::getNotifications();
    }

    public function setNotifications(\Doctrine\Common\Collections\ArrayCollection $notifications)
    {
        $this->__load();
        return parent::setNotifications($notifications);
    }

    public function addNotification(\Fenchy\UserBundle\Entity\Notification $notification)
    {
        $this->__load();
        return parent::addNotification($notification);
    }

    public function removeNotification(\Fenchy\UserBundle\Entity\Notification $notification)
    {
        $this->__load();
        return parent::removeNotification($notification);
    }

    public function getNotificationGroupIntervals()
    {
        $this->__load();
        return parent::getNotificationGroupIntervals();
    }

    public function setNotificationGroupIntervals(\Doctrine\Common\Collections\ArrayCollection $intervals)
    {
        $this->__load();
        return parent::setNotificationGroupIntervals($intervals);
    }

    public function addNotificationGroupInterval(\Fenchy\UserBundle\Entity\NotificationGroupInterval $interval)
    {
        $this->__load();
        return parent::addNotificationGroupInterval($interval);
    }

    public function removeNotificationGroupInterval(\Fenchy\UserBundle\Entity\NotificationGroupInterval $interval)
    {
        $this->__load();
        return parent::removeNotificationGroupInterval($interval);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'name', 'notifications', 'notification_group_intervals');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}