<?php

namespace Proxies\__CG__\Fenchy\RegularUserBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class UserRegular extends \Fenchy\RegularUserBundle\Entity\UserRegular implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function getFirstname()
    {
        $this->__load();
        return parent::getFirstname();
    }

    public function setFirstname($name)
    {
        $this->__load();
        return parent::setFirstname($name);
    }

    public function getLastname()
    {
        $this->__load();
        return parent::getLastname();
    }

    public function setLastname($name)
    {
        $this->__load();
        return parent::setLastname($name);
    }

    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function getGender()
    {
        $this->__load();
        return parent::getGender();
    }

    public function getPrevGender()
    {
        $this->__load();
        return parent::getPrevGender();
    }

    public function setGender($gender)
    {
        $this->__load();
        return parent::setGender($gender);
    }

    public function getBirthday()
    {
        $this->__load();
        return parent::getBirthday();
    }

    public function setBirthday(\DateTime $birthday)
    {
        $this->__load();
        return parent::setBirthday($birthday);
    }

    public function getAge()
    {
        $this->__load();
        return parent::getAge();
    }

    public function setAge($age)
    {
        $this->__load();
        return parent::setAge($age);
    }

    public function getAboutMe()
    {
        $this->__load();
        return parent::getAboutMe();
    }

    public function getPrevAboutMe()
    {
        $this->__load();
        return parent::getPrevAboutMe();
    }

    public function setAboutMe($text)
    {
        $this->__load();
        return parent::setAboutMe($text);
    }

    public function getLink()
    {
        $this->__load();
        return parent::getLink();
    }

    public function getPrevLink()
    {
        $this->__load();
        return parent::getPrevLink();
    }

    public function setLink($link)
    {
        $this->__load();
        return parent::setLink($link);
    }

    public function getUser()
    {
        $this->__load();
        return parent::getUser();
    }

    public function setUser(\Fenchy\UserBundle\Entity\User $user)
    {
        $this->__load();
        return parent::setUser($user);
    }

    public function getGallery($createIfEmpty = true)
    {
        $this->__load();
        return parent::getGallery($createIfEmpty);
    }

    public function setGallery(\Fenchy\GalleryBundle\Entity\Gallery $gallery)
    {
        $this->__load();
        return parent::setGallery($gallery);
    }

    public function setFacebookPublish($facebookPublish)
    {
        $this->__load();
        return parent::setFacebookPublish($facebookPublish);
    }

    public function getFacebookPublish()
    {
        $this->__load();
        return parent::getFacebookPublish();
    }

    public function addMyFriend(\Fenchy\RegularUserBundle\Entity\UserRegular $friend, $revert = true)
    {
        $this->__load();
        return parent::addMyFriend($friend, $revert);
    }

    public function removeMyFriend(\Fenchy\RegularUserBundle\Entity\UserRegular $myFriends, $revert = true)
    {
        $this->__load();
        return parent::removeMyFriend($myFriends, $revert);
    }

    public function getMyFriends()
    {
        $this->__load();
        return parent::getMyFriends();
    }

    public function getPrevMyFriendsQuantity()
    {
        $this->__load();
        return parent::getPrevMyFriendsQuantity();
    }

    public function getMyFriendsIds()
    {
        $this->__load();
        return parent::getMyFriendsIds();
    }

    public function existsFriend(\Fenchy\RegularUserBundle\Entity\UserRegular $myFriend)
    {
        $this->__load();
        return parent::existsFriend($myFriend);
    }

    public function isMyFriend(\Fenchy\RegularUserBundle\Entity\UserRegular $myFriend)
    {
        $this->__load();
        return parent::isMyFriend($myFriend);
    }

    public function countMyFriends()
    {
        $this->__load();
        return parent::countMyFriends();
    }

    public function addFriendsWithMe(\Fenchy\RegularUserBundle\Entity\UserRegular $friendsWithMe)
    {
        $this->__load();
        return parent::addFriendsWithMe($friendsWithMe);
    }

    public function removeFriendsWithMe(\Fenchy\RegularUserBundle\Entity\UserRegular $friendsWithMe)
    {
        $this->__load();
        return parent::removeFriendsWithMe($friendsWithMe);
    }

    public function getFriendsWithMe()
    {
        $this->__load();
        return parent::getFriendsWithMe();
    }

    public function addMyInvitation(\Fenchy\RegularUserBundle\Entity\Invitation $myInvitations)
    {
        $this->__load();
        return parent::addMyInvitation($myInvitations);
    }

    public function addInvitation(\Fenchy\RegularUserBundle\Entity\Invitation $invitation)
    {
        $this->__load();
        return parent::addInvitation($invitation);
    }

    public function removeMyInvitation(\Fenchy\RegularUserBundle\Entity\Invitation $myInvitations)
    {
        $this->__load();
        return parent::removeMyInvitation($myInvitations);
    }

    public function getMyInvitations()
    {
        $this->__load();
        return parent::getMyInvitations();
    }

    public function isInvited(\Fenchy\RegularUserBundle\Entity\UserRegular $regularUser)
    {
        $this->__load();
        return parent::isInvited($regularUser);
    }

    public function addInvitationsForMe(\Fenchy\RegularUserBundle\Entity\Invitation $invitationsForMe)
    {
        $this->__load();
        return parent::addInvitationsForMe($invitationsForMe);
    }

    public function removeInvitationsForMe(\Fenchy\RegularUserBundle\Entity\Invitation $invitationsForMe)
    {
        $this->__load();
        return parent::removeInvitationsForMe($invitationsForMe);
    }

    public function getInvitationsForMe()
    {
        $this->__load();
        return parent::getInvitationsForMe();
    }

    public function setPrefLocale($prefLocale)
    {
        $this->__load();
        return parent::setPrefLocale($prefLocale);
    }

    public function getPrefLocale()
    {
        $this->__load();
        return parent::getPrefLocale();
    }

    public function hasRequiredLocation()
    {
        $this->__load();
        return parent::hasRequiredLocation();
    }

    public function getMainImage()
    {
        $this->__load();
        return parent::getMainImage();
    }

    public function getAvatar($small = true)
    {
        $this->__load();
        return parent::getAvatar($small);
    }

    public function setLanguages($languages)
    {
        $this->__load();
        return parent::setLanguages($languages);
    }

    public function getLanguages()
    {
        $this->__load();
        return parent::getLanguages();
    }

    public function getPrevLanguages()
    {
        $this->__load();
        return parent::getPrevLanguages();
    }

    public function setInterestsAndActivities($str)
    {
        $this->__load();
        return parent::setInterestsAndActivities($str);
    }

    public function getPrevInterestsAndActivities()
    {
        $this->__load();
        return parent::getPrevInterestsAndActivities();
    }

    public function getInterestsAndActivities()
    {
        $this->__load();
        return parent::getInterestsAndActivities();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'firstname', 'lastname', 'gender', 'birthday', 'aboutMe', 'link', 'facebook_publish', 'pref_locale', 'languages', 'user', 'gallery', 'myFriends', 'friendsWithMe', 'myInvitations', 'invitationsForMe');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}